package com.timeline.sqlite;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import com.timeline.bean.MeetingInfo;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig meetingInfoDaoConfig;

    private final MeetingInfoDao meetingInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        meetingInfoDaoConfig = daoConfigMap.get(MeetingInfoDao.class).clone();
        meetingInfoDaoConfig.initIdentityScope(type);

        meetingInfoDao = new MeetingInfoDao(meetingInfoDaoConfig, this);

        registerDao(MeetingInfo.class, meetingInfoDao);
    }
    
    public void clear() {
        meetingInfoDaoConfig.getIdentityScope().clear();
    }

    public MeetingInfoDao getMeetingInfoDao() {
        return meetingInfoDao;
    }

}
